config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  post '/import', to: 'pages#import'
  resources :congressmen, only:[:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/congressman.rb
class Congressman < ApplicationRecord
  has_many :expenses
  validates :name, uniqueness: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :congressman
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/congressmen_controller.rb
class CongressmenController < ApplicationController
  def index
    @congressmen = Congressman.all
    @congressmen_expenses = []
    @congressmen.map do |congressman|
      total = congressman.expenses.sum(:amount) 
      total_spend = {total: total, congressman_id: congressman.id }
      @congressmen_expenses << total_spend
    end
  end

  def show
    @congressman = Congressman.find(params[:id])
    @expenses = @congressman.expenses
  end
end

app/controllers/pages_controller.rb
require 'csv'

class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def home

  end

  def import
    csv_options = { col_sep: ';', encoding: "bom|utf-8", headers: :first_row }
    file = params["csv"].tempfile.path
    uf = "MG"
    csv_data = []
    lala = 0
    CSV.foreach(file, csv_options) do |row|
      if row['sgUF'] == uf
        data = { uf: uf,
                id_cadastro: row['ideCadastro'],
                name: row['txNomeParlamentar'],
                date: row['datEmissao'],
                provider: row['txtFornecedor'],
                amount: row['vlrLiquido'],
                url: row['urlDocumento']
        }
        csv_data << data
        lala += 1
        p lala
      end
    end
    congressmen = []
    expenses = []
    id = 0
    n = 0
    csv_data.each do |data|
      if congressmen.any? { |element| element[:name] == data[:name] }
        congressman_id = congressmen.find {|congressman| congressman[:name] == data[:name] }[:id]
      else 
        id += 1
        congressman = { id: id,
                        uf: uf,
                        id_cadastro: data[:id_cadastro],
                        name: data[:name],
                        created_at: Time.now.utc,
                        updated_at: Time.now.utc
        }
        congressmen << congressman
        congressman_id = id
      end
      n += 1
      expense = { id: n,
                  date: data[:date],
                  provider: data[:provider],
                  amount: data[:amount],
                  url: data[:url],
                  congressman_id: congressman_id,
                  created_at: Time.now.utc,
                  updated_at: Time.now.utc
      }
      expenses << expense
    end

    Congressman.insert_all(congressmen)
    Expense.insert_all(expenses)

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congressmen_helper.rb
module CongressmenHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/congressmen/index.html.erb
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Gasto total</th>
    </tr>
  </thead>

  <tbody>
    <% @congressmen.each do |congressman| %>
      <tr>
        <td><%= link_to "#{congressman.name}", congressman %></td>
        <td><%= @congressmen_expenses.find {|total_expense| total_expense[:congressman_id] == congressman.id }[:total] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/congressmen/show.html.erb
<h2> <%= @congressman.name %> </h2>
<h2> <%= @congressman[:total] %> </h2>
<%= image_tag "https://www.camara.leg.br/internet/deputado/bandep/pagina_do_deputado/#{@congressman.id_cadastro.to_i}.jpg",
    width: 300 %>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Estabelecimento</th>
      <th>Valor</th>
      <th>Link</th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense[:date] %></td>
        <td><%= expense[:provider] %></td>
        <td><%= expense[:amount] %></td>
        <td><%= link_to "URL", expense[:url], target: :_blank %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <div class="page">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<form action="/import" enctype="multipart/form-data" method="post">
  <fieldset>
    <legend>Arquivo</legend>
    <input type="file" name="csv">
    <input type="submit" name="enviar">
  </fieldset>
</form>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item <%= "active" if controller_name == "pages" %>">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= "active" if controller_name == "congressmen" && action_name == "index" %>" >
      <%= link_to "Lista de deputados", congressmen_path, class: "nav-link" %>
    </li>
  </ul>
</div>